# This is a basic workflow to help you get started with Actions

name: Hello DevOps

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest
    env:
     GREETING:"Hello"
       
    steps:
      # Runs a single command using the runners shell
      - name: Say Greeting
        run: echo "${{ env.GREETING }}, ${{ env.TARGET }}!"


