
# This is a basic workflow to help you get started with Actions

name: Hello DevOps

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 14 * * *"  # Runs daily at midnight UTC


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest

    env:
      GREETING: "Greetings"
      TARGET: "Target!"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      # Runs a single command using the runner's shell
      - name: Say Greetings Target
        run: echo "${{ env.GREETING }}, ${{ env.TARGET }}!"
