name: Docker Image CI

on:
  repository_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . docker build . -t devopssandbox
