name: Docker Image CI

on:
  repository_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t devopssandbox:latest

    - uses: actions/checkout@v4
    - name: Run the Docker image
      run: docker run -p 8080:80 devopssandbox:latest
